### ISSUE TITLE
Error with Rocket.Chat=6.7.1 and txtai=7.2.0 and txtchat=0.2.0

### ISSUE THREAD

**Issue by yiouyou** [neuml/txtchat#19]
Error when running 'python -m txtchat.agent wikitalk.yml' with Rocket.Chat=6.7.1 and txtai=7.2.0 and txtchat=0.2.0
```
(txtai) songz:~/txtchat$ python -m txtchat.agent wikitalk.yml
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.17it/s]
Fetching 5 files: 100%|██████████████████████████████████████████████████████████████]██████████████████████████████| 5/5 [00:00<00:00, 13547.49it/s]
2024-04-25 22:52:38,422 [INFO] __call__: Starting agent
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/songz/miniconda3/envs/txtai/lib/python3.11/site-packages/txtchat/agent/__main__.py", line 24, in <module>
    agent()
  File "/home/songz/miniconda3/envs/txtai/lib/python3.11/site-packages/txtchat/agent/base.py", line 43, in __call__
    self.start()
  File "/home/songz/miniconda3/envs/txtai/lib/python3.11/site-packages/txtchat/agent/rocketchat.py", line 46, in start
    asyncio.run(self.run())
  File "/home/songz/miniconda3/envs/txtai/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/songz/miniconda3/envs/txtai/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/songz/miniconda3/envs/txtai/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/songz/miniconda3/envs/txtai/lib/python3.11/site-packages/txtchat/agent/rocketchat.py", line 55, in run
    await self.chat.start(*self.connection())
  File "/home/songz/miniconda3/envs/txtai/lib/python3.11/site-packages/rocketchat_async/core.py", line 38, in start
    self.user_id = await self._login(username, password)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/songz/miniconda3/envs/txtai/lib/python3.11/site-packages/rocketchat_async/core.py", line 80, in _login
    return await Login.call(self._dispatcher, username, password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/songz/miniconda3/envs/txtai/lib/python3.11/site-packages/rocketchat_async/methods.py", line 87, in call
    return cls._parse(response)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/songz/miniconda3/envs/txtai/lib/python3.11/site-packages/rocketchat_async/methods.py", line 80, in _parse
    return response['result']['id']
           ~~~~~~~~^^^^^^^^^^
KeyError: 'result'
```

**Comment by davidmezzetti** [comment]
Likely same as this: https://github.com/neuml/txtchat/issues/17#issuecomment-2551222996
